# Generated by Django 4.0.4 on 2022-04-26 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('fight', models.CharField(choices=[('B', 'Beginner'), ('I', 'intermediate'), ('E', 'Expert')], default='B', max_length=1)),
                ('poke', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.poke')),
            ],
        ),
    ]
