# Generated by Django 4.0.4 on 2022-04-27 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_training'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='date',
            field=models.DateField(verbose_name='training date'),
        ),
        migrations.AlterField(
            model_name='training',
            name='fight',
            field=models.CharField(choices=[('B', 'Beginner'), ('I', 'Intermediate'), ('E', 'Expert')], default='B', max_length=1),
        ),
    ]
